---
### Variables generic to all operating systems
#  this file is loaded automatically if no OS specific file is present

# loaded via the following function in ../tasks/main.yml:
#
# # Load file with variables based on the OS type, or use default if others are not found
# - include_vars: "{{ item }}"
#   with_first_found:
#    - "../vars/{{ ansible_distribution }}.yml"
#    - "../vars/{{ ansible_os_family }}.yml"
#    - "../vars/default.yml"


# examples:
# ntp_daemon: "ntpd"

example_var: ""
